<?xml version="1.0" encoding="utf-8"?>
<!-- this file is not in use! but i want to keep it anyways for now... -->
<xsl:stylesheet
  version="1.0"
  xmlns="http://schemas.microsoft.com/wix/2006/wi"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:wix="http://schemas.microsoft.com/wix/2006/wi"
  xmlns:str="http://xsltsl.org/string"
  exclude-result-prefixes="wix str"  
  >

  <xsl:output
	encoding="utf-8"
	method="xml"
	version="1.0"
	indent="yes"	
	/>

  <xsl:template match='wix:Component'> 
	<xsl:copy>
		<xsl:apply-templates select="@*"/>
		<xsl:attribute name="Win64">yes</xsl:attribute>
		<xsl:apply-templates select="node()"/>
	</xsl:copy>
  </xsl:template>

  <!-- identity template -->
  <xsl:template match="@*|node()">
	<xsl:copy>
	  <xsl:apply-templates select="@*|node()"/>
	</xsl:copy>
  </xsl:template>

  <xsl:template match='/'>
	<xsl:comment>*** DO NOT EDIT: Generated by heat.exe; transformed by wix_heat.xsl</xsl:comment>
	<xsl:apply-templates select="@*|node()"/>
  </xsl:template>

</xsl:stylesheet>